---
name: publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set version
      uses: actions/github-script@v4
      id: set_version
      with:
        script: |
          console.log(context)
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: deesel/wol:${GITHUB_REF_NAME##v}
